### PR TITLE
Converted site to tailwind css

### PR DESCRIPTION
**Pull request by Corcso**
Site is pretty much the same, styling isn't identical but would have taken ages to replicate the exact same as using a different framework. I think the site looks more modern anyways. 

Uses the tailwind CDN for the library (don't think its too recommended but probably ok for our purposes). Config file only exists to work with VScode intellisence  

Bootstrap CDN might still be there but is an easy removal. 1 line per file.

### CODE REVIEW

**Comment by greghuc** [comment]
This is excellent. Nice one.

Please do some small tweaks before we go live with this. Not expecting perfection, but I'd like the new site to look "good enough" before replacing the old one. Can then make bigger improvements later if needed.

First tweak is.. please replicate the vertical spacing of the current site better (mainly between paragraphs, and buttons).

My brief investigation suggests the fix is `space-y-{amount}`:
* https://tailwindcss.com/docs/space#add-vertical-space-between-children
* https://tailwind-elements.com/docs/standard/extended/paragraph-spacing/

Will then review again.

**Comment by Corcso** [comment]
@greghuc I've added spacing as mentioned, here is the commit description for quick reading. 

> Space-y-3 was added to all text sections, the badge/challenge boxes were fine and the button things on the front page are using margins on the elements as the button's box model is behaving differently. 

Let me know if anything is further required.

**Comment by greghuc** [comment]
Much improved. Almost there. Please do some more spacing fixes, and then we can merge. Here's what I've seen, but please check yourself. All I'm doing is loading up coderdojostirling.com, and comparing it side by side with tailwind form. Doesn't need to be identical, but current coderdojostirling.com spacing is decent. Could also do some tweaks in person tomorrow.

Spacing issues I saw:

index.html
* more spacing between 3 points below “We are CoderDojo Stirling” header

earn-badges.html
* bit more spacing above and below each badge header

do-challenges.html
* bit more spacing below each challenge header
* some of the spacing is off on some challenge paragraphs (likely crap html). e.g. search for “to the moon”
* might be worth a scan through all the challenges to fix up worst spacing examples

come-along.html
- “We have some spare laptops”

general
* copyright

**Comment by Corcso** [comment]
Fixed all listed above apart from 
>might be worth a scan through all the challenges to fix up worst spacing examples

as I do not have time right now will do tomorrow at the dojo.

**Comment by greghuc** [comment]
So I'm merging this pr as the site looks decent enough - many thanks.

Will now add this month's challenges, and we can then make follow on tweaks.

**Pull request merged**
